version: "3.9"
services:
  postgres:
    container_name: db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"
  my_crud:
    restart: always
    build: ./
    command:
      - ./my_crud
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=root